@extends('layouts.app')
@section('title', 'Extras')
@section('eyebrow', 'Catalog management')
@section('heading', 'Extras')
@section('subtitle', 'Maintain reusable add-ons that can be attached to customer orders.')
@section('content')
<section class="overview-metrics" aria-label="Extra metrics"><article class="metric-card"><span>Total extras</span><strong>{{ $metrics['total_extras'] }}</strong></article><article class="metric-card"><span>Created today</span><strong>{{ $metrics['created_today'] }}</strong></article><article class="metric-card"><span>Top reason</span><strong>{{ $metrics['top_reason'] }}</strong></article><article class="metric-card"><span>Used in confirmations</span><strong>{{ $metrics['used_in_confirmations'] }}</strong></article></section>
<div class="workspace-page catalog-admin-page">
    @if(session('status'))<div class="catalog-notice" role="status">{{ session('status') }}</div>@endif
    <section class="surface-card"><div class="card-head"><div><p class="eyebrow">Create note</p><h2>New Extra Comment</h2></div><span class="section-note">Internal dashboard note</span></div><form method="POST" action="{{ route('admin.extras.store') }}" class="service-form-grid">@csrf<label class="field readonly"><span>Extra ID</span><input value="Generated on save" readonly></label><label class="field readonly"><span>Created Date</span><input value="{{ now()->format('d M Y, H:i') }}" readonly></label><label class="field wide"><span>Created For Why</span><input name="reason" placeholder="Why was this note created?"></label><label class="field wide"><span>Internal Description</span><textarea name="description" rows="3" placeholder="Visible only inside the dashboard"></textarea></label><label class="field"><span>Order Visible Short Note</span><input name="short_note" maxlength="24" placeholder="Late arrival"></label><label class="field"><span>Extra Name</span><input name="title" required></label><label class="field"><span>Slug</span><input name="slug" required></label><label class="field"><span>Price (EGP)</span><input name="base_price" type="number" min="0" step="0.01" required></label><label class="field"><span>Sort order</span><input name="sort_order" type="number" min="0" value="0"></label><div class="form-actions catalog-form-actions"><button class="ui-button primary" type="submit">Save Extra</button></div></form></section>
    <section class="surface-card"><div class="card-head"><div><p class="eyebrow">History</p><h2>Available Extras List</h2></div><span class="section-note">Manage active extras and temporarily remove them from order selection</span></div><div class="data-table-shell"><table><thead><tr><th>Extra ID</th><th>Created Date</th><th>Extra Name</th><th>Reason</th><th>Short note</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($extras as $extra)<tr><td>#EXT-{{ $extra->id }}</td><td>{{ $extra->created_at?->format('d M Y, H:i') }}</td><td><strong>{{ $extra->title }}</strong><small>{{ $extra->slug }}</small></td><td>{{ $extra->reason ?: '—' }}</td><td>{{ $extra->short_note ?: '—' }}</td><td>{{ $extra->is_active ? 'Active' : 'Paused' }}</td><td><form method="POST" action="{{ route('admin.extras.toggle', $extra) }}">@csrf @method('PATCH')<button class="table-action-btn edit" type="submit">{{ $extra->is_active ? 'Pause' : 'Activate' }}</button></form></td></tr>@empty<tr><td colspan="7" class="empty-table">No extras created yet.</td></tr>@endforelse</tbody></table></div>{{ $extras->links() }}</section>
</div>
@endsection
