const q=id=>document.getElementById(id),read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v)),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const seeds=[
{id:"APR-26081",type:"Finance",subject:"Customer wallet adjustment",target:"USR-102938 / Mariam Kamal",requestedBy:"Sara Nabil",requesterRole:"Supporter",before:"EGP 420",after:"EGP 920",priority:"Urgent",submittedAt:"2026-08-18T09:20:00",reason:"Compensation approved after a duplicated wallet charge.",evidence:"wallet-case-102938.pdf",status:"Pending"},
{id:"APR-26082",type:"Partners",subject:"Partner commission change",target:"OP-1024 / Mona Adel",requestedBy:"Omar Hassan",requesterRole:"Finance Editor",before:"18%",after:"20%",priority:"Normal",submittedAt:"2026-08-18T08:45:00",reason:"Temporary commission increase for the August performance target.",evidence:"commission-review.xlsx",status:"Pending"},
{id:"APR-26083",type:"Orders",subject:"Paid order cancellation refund",target:"ORD-9402 / Nada Fathy",requestedBy:"Dina Adel",requesterRole:"Supporter",before:"Confirmed / EGP 2,100",after:"Cancelled / Full refund",priority:"Urgent",submittedAt:"2026-08-18T08:10:00",reason:"Customer reported an emergency before partner handover.",evidence:"customer-confirmation.pdf",status:"Pending"},
{id:"APR-26084",type:"Maids",subject:"Maid salary update",target:"MD-1098 / Hoda Ali",requestedBy:"Ahmed Fathy",requesterRole:"Operations Editor",before:"EGP 9,200",after:"EGP 9,800",priority:"Normal",submittedAt:"2026-08-17T16:35:00",reason:"Monthly performance review and completed-order target achieved.",evidence:"performance-august.pdf",status:"Pending"},
{id:"APR-26079",type:"Pricing",subject:"Gold Package price change",target:"PKG-204 / Gold Package",requestedBy:"Youssef Ali",requesterRole:"Pricing Editor",before:"EGP 1,850",after:"EGP 1,950",priority:"Normal",submittedAt:"2026-08-17T10:15:00",reason:"Supplier and operating cost adjustment.",evidence:"pricing-sheet.pdf",status:"Approved",decidedBy:"Super Admin",decidedAt:"2026-08-18T07:40:00",decisionNote:"Approved for the next publishing cycle."},
{id:"APR-26077",type:"Partners",subject:"Pause partner account",target:"OP-1057 / Ahmed Fathy",requestedBy:"Karim Samir",requesterRole:"Supporter",before:"Active",after:"Paused",priority:"Urgent",submittedAt:"2026-08-16T13:30:00",reason:"Incomplete contract renewal documents.",evidence:"document-check.pdf",status:"Rejected",decidedBy:"Super Admin",decidedAt:"2026-08-17T14:05:00",decisionNote:"Partner submitted valid renewal documents before the deadline."}
];
let requests=read("approvalCenterRequests",null);if(!Array.isArray(requests)){requests=seeds;write("approvalCenterRequests",requests)}
let currentView="pending",activeId=null,decisionType=null;
const today=()=>new Date().toISOString().slice(0,10),formatDate=v=>new Date(v).toLocaleString("en-GB",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"});
function filtered(){const term=q("approvalSearch").value.trim().toLowerCase(),type=q("typeFilter").value,priority=q("priorityFilter").value;return requests.filter(r=>(currentView==="pending"?r.status==="Pending":r.status!=="Pending")&&(type==="all"||r.type===type)&&(priority==="all"||r.priority===priority)&&[r.id,r.subject,r.target,r.requestedBy,r.type].join(" ").toLowerCase().includes(term))}
function metrics(){const date=today();q("pendingMetric").textContent=requests.filter(r=>r.status==="Pending").length;q("urgentMetric").textContent=requests.filter(r=>r.status==="Pending"&&r.priority==="Urgent").length;q("approvedMetric").textContent=requests.filter(r=>r.status==="Approved"&&r.decidedAt?.slice(0,10)===date).length;q("rejectedMetric").textContent=requests.filter(r=>r.status==="Rejected"&&r.decidedAt?.slice(0,10)===date).length;localStorage.setItem("approvalPendingCount",String(requests.filter(r=>r.status==="Pending").length));document.dispatchEvent(new CustomEvent("approval-count-updated"))}
function render(){const rows=filtered();q("approvalTableBody").innerHTML=rows.map(r=>'<tr><td><div class="request-cell"><strong>'+esc(r.subject)+'</strong><span>'+r.id+' / '+esc(r.target)+'</span></div></td><td>'+r.type+'</td><td><strong>'+esc(r.requestedBy)+'</strong><div class="muted">'+esc(r.requesterRole)+'</div></td><td><div class="change-cell"><span>'+esc(r.before)+'</span><b>To: '+esc(r.after)+'</b></div></td><td><span class="pill '+r.priority.toLowerCase()+'">'+r.priority+'</span></td><td>'+formatDate(r.submittedAt)+'</td><td><span class="pill '+r.status.toLowerCase()+'">'+r.status+'</span></td><td><div class="actions"><button class="table-btn" data-view-id="'+r.id+'" type="button">View</button>'+(r.status==="Pending"?'<button class="table-btn approve" data-approve-id="'+r.id+'" type="button">Approve</button><button class="table-btn reject" data-reject-id="'+r.id+'" type="button">Reject</button>':"")+'</div></td></tr>').join("");q("approvalEmpty").classList.toggle("hidden",rows.length>0);bindRows();metrics()}
function bindRows(){document.querySelectorAll("[data-view-id]").forEach(b=>b.onclick=()=>openDetails(b.dataset.viewId));document.querySelectorAll("[data-approve-id]").forEach(b=>b.onclick=()=>openDecision(b.dataset.approveId,"Approved"));document.querySelectorAll("[data-reject-id]").forEach(b=>b.onclick=()=>openDecision(b.dataset.rejectId,"Rejected"))}
function detailBody(r){return '<div class="detail-grid"><div class="detail-item"><span>Request ID</span><strong>'+r.id+'</strong></div><div class="detail-item"><span>Requested By</span><strong>'+esc(r.requestedBy)+'</strong></div><div class="detail-item"><span>Submitted</span><strong>'+formatDate(r.submittedAt)+'</strong></div></div><div class="change-panel"><div class="change-column"><span>Current Value</span><strong>'+esc(r.before)+'</strong></div><div class="change-arrow">-&gt;</div><div class="change-column"><span>Requested Value</span><strong>'+esc(r.after)+'</strong></div></div><div class="reason-panel"><strong>Business Reason</strong><p>'+esc(r.reason)+'</p></div><div class="evidence-row"><span>Supporting File</span><strong>'+esc(r.evidence||"No attachment")+'</strong></div>'+(r.status!=="Pending"?'<div class="reason-panel"><strong>'+r.status+' by '+esc(r.decidedBy)+'</strong><p>'+esc(r.decisionNote)+'</p><span class="muted">'+formatDate(r.decidedAt)+'</span></div>':"")}
function showModal(r){activeId=r.id;q("approvalModalTitle").textContent=r.subject;q("approvalModalEyebrow").textContent=r.type+" Approval";q("approvalModalBody").innerHTML=detailBody(r);q("approvalModal").classList.remove("hidden");q("approvalModal").setAttribute("aria-hidden","false")}
function openDetails(id){const r=requests.find(x=>x.id===id);if(!r)return;decisionType=null;showModal(r);q("decisionForm").classList.add("hidden");q("confirmDecisionBtn").classList.add("hidden");q("approveRequestBtn").classList.toggle("hidden",r.status!=="Pending");q("rejectRequestBtn").classList.toggle("hidden",r.status!=="Pending")}
function openDecision(id,type){const r=requests.find(x=>x.id===id);if(!r||r.status!=="Pending")return;showModal(r);decisionType=type;q("approveRequestBtn").classList.add("hidden");q("rejectRequestBtn").classList.add("hidden");q("decisionForm").classList.remove("hidden");q("confirmDecisionBtn").classList.remove("hidden");q("confirmDecisionBtn").textContent="Confirm "+type;q("decisionNoteLabel").textContent=type==="Rejected"?"Rejection Reason *":"Approval Note";q("decisionNote").value="";q("decisionError").textContent="";q("decisionNote").focus()}
function confirmDecision(){const r=requests.find(x=>x.id===activeId),note=q("decisionNote").value.trim();if(!r)return;if(decisionType==="Rejected"&&!note){q("decisionError").textContent="A rejection reason is required.";q("decisionNote").focus();return}const finalDecision=decisionType;r.status=finalDecision;r.decidedBy="Super Admin";r.decidedAt=new Date().toISOString();r.decisionNote=note||(finalDecision+" after reviewing the submitted evidence.");write("approvalCenterRequests",requests);closeModal();render();toast(r.id+" was "+finalDecision.toLowerCase()+".")}
function closeModal(){q("approvalModal").classList.add("hidden");q("approvalModal").setAttribute("aria-hidden","true");activeId=null;decisionType=null}
function setView(view){currentView=view;document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===view));q("tableEyebrow").textContent=view==="pending"?"Decision Queue":"Audit History";q("tableTitle").textContent=view==="pending"?"Pending Approval Requests":"Approval Decision History";q("showHistoryBtn").textContent=view==="pending"?"Show History":"Show Pending";render()}
function toast(m){q("approvalToast").textContent=m;q("approvalToast").classList.remove("hidden");clearTimeout(toast.timer);toast.timer=setTimeout(()=>q("approvalToast").classList.add("hidden"),2600)}
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>setView(b.dataset.view));["approvalSearch","typeFilter","priorityFilter"].forEach(id=>q(id).addEventListener(id==="approvalSearch"?"input":"change",render));q("clearApprovalFilters").onclick=()=>{q("approvalSearch").value="";q("typeFilter").value="all";q("priorityFilter").value="all";render()};q("showHistoryBtn").onclick=()=>setView(currentView==="pending"?"history":"pending");q("refreshApprovalsBtn").onclick=()=>{requests=read("approvalCenterRequests",seeds);render();toast("Approval queue refreshed.")};q("approvalModalClose").onclick=closeModal;q("approvalModalSecondary").onclick=closeModal;q("approveRequestBtn").onclick=()=>openDecision(activeId,"Approved");q("rejectRequestBtn").onclick=()=>openDecision(activeId,"Rejected");q("confirmDecisionBtn").onclick=confirmDecision;q("approvalModal").onclick=e=>{if(e.target===q("approvalModal"))closeModal()};document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});render();