@extends('layouts.app')
@section('title', 'Slider Ads')
@section('eyebrow', 'Marketing')
@section('heading', 'Slider Ads')
@section('subtitle', 'Schedule promotional placements and monitor their delivery.')
@section('content')
<section class="overview-metrics" aria-label="Ad metrics"><article class="metric-card"><span>Active ads</span><strong>{{ $metrics['active_ads'] }}</strong></article><article class="metric-card"><span>Scheduled ads</span><strong>{{ $metrics['scheduled_ads'] }}</strong></article><article class="metric-card"><span>Top slot</span><strong>{{ $metrics['top_slot'] }}</strong></article><article class="metric-card"><span>Clicks</span><strong>{{ $metrics['clicks'] }}</strong></article></section>
<div class="workspace-page"><section class="surface-card"><div class="card-head"><div><p class="eyebrow">New campaign</p><h2>Create ad</h2></div></div>@if(session('status'))<div class="catalog-notice" role="status">{{ session('status') }}</div>@endif<form method="POST" action="{{ route('admin.ads.store') }}" class="service-form-grid">@csrf<label class="field"><span>Title</span><input name="title" required></label><label class="field"><span>Slot</span><input name="slot_name" required></label><label class="field"><span>Destination URL</span><input name="destination" type="url" required></label><label class="field"><span>Image URL</span><input name="image_url" type="url"></label><label class="field"><span>Starts at</span><input name="starts_at" type="datetime-local"></label><label class="field"><span>Ends at</span><input name="end_date" type="datetime-local"></label><label class="field wide"><span>Description</span><textarea name="description" rows="2"></textarea></label><button class="ui-button primary" type="submit">Create ad</button></form></section><section class="surface-card"><div class="card-head"><div><p class="eyebrow">Campaign directory</p><h2>Ads history</h2></div></div><div class="data-table-shell"><table><thead><tr><th>Title</th><th>Slot</th><th>Schedule</th><th>Reach</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($ads as $ad)<tr><td>{{ $ad->title }}</td><td>{{ $ad->slot_name }}</td><td>{{ $ad->starts_at?->format('d M Y') ?? 'Now' }} → {{ $ad->end_date?->format('d M Y') ?? 'Open' }}</td><td>{{ number_format($ad->impressions) }} / {{ number_format($ad->clicks) }}</td><td>{{ ucfirst($ad->status) }}</td><td><form method="POST" action="{{ route('admin.ads.toggle', $ad) }}">@csrf @method('PATCH')<button class="table-action-btn edit" type="submit">{{ $ad->status === 'active' ? 'Pause' : 'Activate' }}</button></form></td></tr>@empty<tr><td colspan="6" class="empty-table">No ads created yet.</td></tr>@endforelse</tbody></table></div>{{ $ads->links() }}</section></div>
@endsection
