@extends('layouts.app')
@section('title', 'Approval Center')
@section('eyebrow', 'Governance and control')
@section('heading', 'Approval Center')
@section('subtitle', 'Review sensitive changes and record a decision with an auditable note.')
@section('content')
<section class="overview-metrics" aria-label="Approval metrics"><article class="metric-card"><span>Pending</span><strong>{{ $metrics['pending'] }}</strong></article><article class="metric-card"><span>Urgent</span><strong>{{ $metrics['urgent'] }}</strong></article><article class="metric-card"><span>Approved today</span><strong>{{ $metrics['approved_today'] }}</strong></article><article class="metric-card"><span>Rejected today</span><strong>{{ $metrics['rejected_today'] }}</strong></article></section>
<div class="workspace-page"><section class="surface-card"><div class="card-head"><div><p class="eyebrow">Decision queue</p><h2>Approval requests</h2></div></div>@if(session('status'))<div class="catalog-notice" role="status">{{ session('status') }}</div>@endif<div class="data-table-shell"><table><thead><tr><th>Subject</th><th>Type</th><th>Requested by</th><th>Priority</th><th>Status</th><th>Decision</th></tr></thead><tbody>@forelse($requests as $approval)<tr><td>{{ $approval->subject }}</td><td>{{ $approval->type }}</td><td>{{ $approval->requester?->name ?? 'System' }}</td><td>{{ ucfirst($approval->priority) }}</td><td>{{ ucfirst($approval->status) }}</td><td>@if($approval->status === 'pending')<form method="POST" action="{{ route('admin.approvals.decide', $approval) }}" class="inline-form">@csrf @method('PATCH')<select name="status" required><option value="approved">Approve</option><option value="rejected">Reject</option></select><input name="decision_note" placeholder="Decision note" required><button class="ui-button primary" type="submit">Record</button></form>@else{{ $approval->decision_note ?: '—' }}@endif</td></tr>@empty<tr><td colspan="6" class="empty-table">No approval requests.</td></tr>@endforelse</tbody></table></div>{{ $requests->links() }}</section></div>
@endsection
